version: "3.8"

services:
  webapp:
    container_name: modec-tech-challenge-webapp
    image: node:21-bookworm
    ports: 
      - $NEXT_PUBLIC_WEBAPP_PORT:$NEXT_PUBLIC_WEBAPP_PORT
    restart: always
    working_dir: /webapp
    build:
      context: ./webapp
    volumes:
      - ./webapp:/webapp
      - ./.env:/webapp/.env
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
  db:
    container_name: modec-tech-challenge-db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./database/:/database/
      - ./database/employees.csv:/var/lib/mysql-files/employees.csv
      - ./database/populate.sql:/docker-entrypoint-initdb.d/populate.sql
      - ./.env:/.env
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
